# Generated by Django 2.2.3 on 2019-10-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese su nombre.', max_length=20)),
                ('apellido', models.CharField(help_text='Ingrese su apellido.', max_length=20)),
                ('horario', models.TimeField(help_text='Ingrese el horario que tenga disponible.')),
                ('nota', models.TextField(blank=True, help_text='(*Opcional.)')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
    ]
