# Generated by Django 2.2.3 on 2019-11-01 19:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese su nombre.', max_length=20)),
                ('apellido', models.CharField(help_text='Ingrese su apellido.', max_length=20)),
                ('horario', models.TimeField(help_text='Ingrese el horario que tenga disponible.')),
                ('motivo', models.CharField(choices=[('Escolar', 'Escolar'), ('Personal', 'Personal')], default='Escolar', help_text='Ingrese aquí el motivo.', max_length=1)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(help_text='Ingrese su teléfono.', max_length=128, region=None, verbose_name='Teléfono')),
                ('email', models.EmailField(help_text='Ingrese aquí su email.', max_length=254)),
                ('nota', models.TextField(blank=True, help_text='(*Opcional.)')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
    ]
