# Generated by Django 2.2.3 on 2019-10-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asesoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='horario',
            field=models.TimeField(help_text='Ingrese el horario que tenga disponible.', null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='notas',
            field=models.TextField(blank=True, help_text='(*Opcional.)'),
        ),
    ]
